# Generated by Django 3.0.5 on 2021-02-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=500)),
                ('body', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
